#!/bin/sh

. wmrc

coord="70"
X=$coord
Y=$coord
num=$coord/$BW

case $1 in
    tr) X=$((SW - W - BW*$num)) ;;
    bl) Y=$((SH - H - BW*$num)) ;;
    br) X=$((SW - W - BW*$num))
        Y=$((SH - H - BW*$num)) ;;
    md) X=$((SW/2 - W/2 - BW))
        Y=$((SH/2 - H/2 - BW));;
esac

wtp $X $Y $W $H $CUR
