#!/bin/sh

type wew 2>&1 > /dev/null || {
    cat >&2 << EOF
wew was not found on your path. This means you likely don't have the wmutils
tools installed. You can install wmtuils from these repositories from github:
core - https://github.com/wmutils/core
opt - https://github.com/wmutils/opt
EOF
    exit 1
}
type xprop 2>&1 > /dev/null || {
    cat >&2 << EOF
xprop was not found on your path. You need xprop so fyre can detect what
properties a window has i.e. the window's name and class. You can install xprop
by searching for 'xorg-xprop' (or similar) using your package manager.
EOF

    exit 1
}

. wmrc


grps -C
test -f $HOVER && rm -f $HOVER
test -f $FSFILE && rm -f $FSFILE
test -f $SCREENS && rm -f $SCREENS

# set background if WALL set
wall
# let the event watcher loop keep the X11 connection open
fw
